name: Run Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Python-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
  
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
  
    - name: Add poetry to our path
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
  
  
    - name: Run poetry install
      run: poetry install
      
    - name: Run Tests
      run: poetry run pytest
